ALTER TABLE rooms ADD COLUMN IF NOT EXISTS max_adults INT NOT NULL DEFAULT 2;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS max_children INT NOT NULL DEFAULT 2;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS child_policy TEXT NOT NULL DEFAULT '';

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS children INT NOT NULL DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS units INT NOT NULL DEFAULT 1;
