import type { Hotel, Scene } from "@/types/hotel";

/**
 * Each scene has a fixed pitch (mostly slight-up to show the property) and
 * a fixed FOV. The YAW is GLOBAL and auto-rotates over time so the user
 * sees the full 360° like a slow video pan. Transitions between scenes
 * are zoom-out / crossfade / zoom-in.
 *
 * Pitch is POSITIVE in YXZ Euler (looking up at the carved ceiling, the
 * lake, the architecture — not the floor).
 */
const cam = (pitch: number, fov: number, startYaw?: number): Scene["camera"] => ({
  pitch,
  fov,
  startYaw,
});

export const hotel: Hotel = {
  id: "houseboat-canberra",
  slug: "houseboat-canberra-srinagar",
  name: "Houseboat Canberra",
  tagline: "A Heritage Sanctuary on Dal Lake",
  description:
    "Cedar-panelled suites, hand-knotted Kashmiri carpets and the stillness of the lake at dawn. Houseboat Canberra is a discreet, family-run residence that has welcomed travellers to Srinagar for over four decades.",
  location: {
    city: "Srinagar",
    region: "Jammu & Kashmir",
    country: "India",
    coordinates: { lat: 34.1283, lng: 74.8347 },
  },
  contact: {
    phone: "+49 176 84005474",
    email: "Houseboat.canberra@gmail.com",
    address: "Gate no 13, Dal Lake Boulevard Road, Srinagar, 190001, Jammu and Kashmir, India",
    mapsUrl: "https://maps.app.goo.gl/SksBEMezBTQxYJFS8",
    whatsapp: "4917684005474",
    whatsappQr: "/whatsapp-qr.png",
  },
  brand: {
    primary: "#0E1411",
    secondary: "#E9DFCE",
    accent: "#C8A86B",
  },
  offers: [
    { id: "lake-stay", title: "Lakeside Reverie", description: "Two nights with breakfast and a private shikara at sunset.", code: "LAKE24", discount: "15%" },
    { id: "extended", title: "Slow Kashmir", description: "Stay five nights, pay for four. Includes airport transfer.", code: "SLOW5" },
    { id: "heritage", title: "Heritage Suite Upgrade", description: "Complimentary upgrade to the Deluxe Heritage Suite." },
  ],
  social: [
    {
      label: "Instagram",
      href: "https://www.instagram.com/houseboatcanberra",
    },
    {
      label: "Facebook",
      href: "https://www.facebook.com/people/Houseboat-Canberra/61553670362440/",
    },
  ],
  scenes: [
    {
      id: "arrival",
      index: 0,
      name: "Arrival",
      kicker: "Chapter 01",
      scrollAnchor: 0.02,
      panorama: "/panoramas/garden-1.jpg",
      camera: cam(0.15, 65, Math.PI / 2),
      theme: "light",
      headline: "Approach in silence.",
      body: "A cedar pathway, lined with marigolds, leads you from the boulevard of Dal Lake directly to the gangway of Canberra.",
      hotspots: [],
    },
    {
      id: "deck",
      index: 1,
      name: "The Deck",
      kicker: "Chapter 02",
      scrollAnchor: 0.1,
      panorama: "/panoramas/deck-main.jpg",
      camera: cam(0.30, 60, Math.PI / 2),
      theme: "light",
      headline: "Where the lake becomes the lobby.",
      body: "Hand-carved walnut loungers, willow blinds and the gentle putter of shikaras drifting past.",
      hotspots: [],
      amenities: [
        { id: "deck-sun", title: "Sun Deck", description: "Open-air lounging with lake views.", icon: "sun", highlightIn: ["deck"] },
        { id: "deck-shi", title: "Private Shikara", description: "Wooden boat at the gangway, on call.", icon: "boat", highlightIn: ["deck"] },
        { id: "deck-kah", title: "Kahwa Service", description: "Saffron & cardamom tea, served at sunset.", icon: "tea", highlightIn: ["deck"] },
      ],
    },
    {
      id: "living",
      index: 2,
      name: "Living Room",
      kicker: "Chapter 03",
      scrollAnchor: 0.2,
      panorama: "/panoramas/living.jpg",
      camera: cam(0.18, 60, 0),
      theme: "dark",
      headline: "A library carved in walnut.",
      body: "Tall windows, deep sofas, a fireplace in winter. The social heart of the houseboat.",
      hotspots: [],
    },
    {
      id: "reception",
      index: 3,
      name: "Corridor",
      kicker: "Chapter 04",
      scrollAnchor: 0.3,
      panorama: "/panoramas/corridor-main.jpg",
      camera: cam(0.10, 60, 0),
      theme: "dark",
      headline: "Past the gates of the cedar hallway.",
      body: "Woven crewel runners underfoot, dimmed lantern light overhead, the corridor leads to every suite.",
      hotspots: [],
    },
    {
      id: "deluxe",
      index: 4,
      name: "Deluxe Room",
      kicker: "Chapter 05",
      scrollAnchor: 0.4,
      panorama: "/panoramas/bedroom-1.jpg",
      camera: cam(0.15, 60, 0),
      theme: "dark",
      headline: "Linen, light, lake.",
      body: "Queen bed dressed in crisp cotton, a writing desk by the window, a private washroom in Pashmina marble.",
      room: {
        id: "deluxe",
        name: "Deluxe Heritage Room",
        tagline: "Lake-facing, queen-bedded",
        description: "Our signature room. Walnut panelling, a queen bed with hand-loomed Kashmiri throws, a private sit-out and an attached washroom finished in pale Pashmina marble.",
        size: "260 sq ft",
        occupancy: "2 adults",
        bedType: "Queen",
        amenities: ["Lake-facing window", "Private sit-out", "Attached marble washroom", "Tea & coffee maker", "Heating"],
        view: "Dal Lake",
        priceFrom: 11500,
        currency: "INR",
        availability: "available",
        gallery: [
          { src: "/panoramas/bedroom-1.jpg", alt: "Deluxe Room" },
          { src: "/panoramas/bedroom-1-dressing.jpg", alt: "Dressing area" },
          { src: "/panoramas/washroom-1.jpg", alt: "Washroom" },
        ],
        panorama: "/panoramas/bedroom-1.jpg",
      },
      hotspots: [],
    },
    {
      id: "executive",
      index: 5,
      name: "Executive Room",
      kicker: "Chapter 06",
      scrollAnchor: 0.5,
      panorama: "/panoramas/bedroom-2.jpg",
      camera: cam(0.12, 60, 0),
      theme: "dark",
      headline: "A larger canvas of cedar and lake.",
      body: "King bed, twin reading nooks, an extended wardrobe and a deep claw-foot tub.",
      room: {
        id: "executive",
        name: "Executive Lake Suite",
        tagline: "King-bedded with extended sit-out",
        description: "A more generous suite for longer stays — king bed, two reading chairs by the windows, walk-in wardrobe, and a washroom with a freestanding tub.",
        size: "380 sq ft",
        occupancy: "2 adults",
        bedType: "King",
        amenities: ["King bed", "Walk-in wardrobe", "Freestanding tub", "Twin reading nooks", "Private sit-out", "Heating"],
        view: "Dal Lake",
        priceFrom: 16900,
        currency: "INR",
        availability: "limited",
        gallery: [
          { src: "/panoramas/bedroom-2.jpg", alt: "Executive Room" },
          { src: "/panoramas/bedroom-2-alt.jpg", alt: "Alternate view" },
          { src: "/panoramas/washroom-2.jpg", alt: "Washroom" },
        ],
        panorama: "/panoramas/bedroom-2.jpg",
      },
      hotspots: [],
    },
    {
      id: "family",
      index: 6,
      name: "Family Suite",
      kicker: "Chapter 07",
      scrollAnchor: 0.6,
      panorama: "/panoramas/bedroom-3.jpg",
      camera: cam(0.15, 60, Math.PI / 2),
      theme: "dark",
      headline: "Two rooms, one lake, no compromises.",
      body: "An interconnecting suite of two bedrooms, two washrooms and a private lounge — designed for families travelling together.",
      room: {
        id: "family",
        name: "Family Lake Suite",
        tagline: "Interconnecting two-bedroom suite",
        description: "Two interconnecting bedrooms, a private lounge, and two washrooms. A discrete entrance, ideal for multi-generational travel.",
        size: "560 sq ft",
        occupancy: "4 adults + 1 child",
        bedType: "1 King + 2 Twin",
        amenities: ["Two bedrooms", "Private lounge", "Two washrooms", "Lake-facing windows", "Heating", "Family dining on request"],
        view: "Dal Lake",
        priceFrom: 24500,
        currency: "INR",
        availability: "available",
        gallery: [
          { src: "/panoramas/bedroom-3.jpg", alt: "Family Suite" },
          { src: "/panoramas/bedroom-3-dressing.jpg", alt: "Dressing" },
          { src: "/panoramas/living-2.jpg", alt: "Private lounge" },
          { src: "/panoramas/washroom-3.jpg", alt: "Washroom" },
        ],
        panorama: "/panoramas/bedroom-3.jpg",
      },
      hotspots: [],
    },
    {
      id: "dining",
      index: 7,
      name: "Dining",
      kicker: "Chapter 08",
      scrollAnchor: 0.7,
      panorama: "/panoramas/dining.jpg",
      camera: cam(0.12, 60, 0),
      theme: "dark",
      headline: "Wazwan, by the water.",
      body: "Wicker-back chairs, bone china, candle-glass — a six-table dining room serving Wazwan, fresh trout and the breads of the valley.",
      hotspots: [],
      amenities: [
        { id: "wazwan", title: "Wazwan Tasting", description: "Seven-course traditional feast.", icon: "plate", highlightIn: ["dining"] },
        { id: "trout", title: "Trout from the Lake", description: "Line-caught, cooked in walnut.", icon: "fish", highlightIn: ["dining"] },
        { id: "kahwa2", title: "Kahwa & Bakery", description: "Morning breads and saffron tea.", icon: "tea", highlightIn: ["dining"] },
      ],
    },
    {
      id: "spa",
      index: 8,
      name: "Wellness",
      kicker: "Chapter 09",
      scrollAnchor: 0.8,
      panorama: "/panoramas/garden-1.jpg",
      camera: cam(0.20, 60, 0),
      theme: "light",
      headline: "Quiet. Warmth. The sound of water.",
      body: "A small spa on the upper deck — massages with mustard oil, outdoor yoga at sunrise, and easy access to scenic waterfront walks and nature trails.",
      hotspots: [],
      amenities: [
        { id: "massage", title: "Kashmiri Massage", description: "Mustard oil and slow hands.", icon: "hand", highlightIn: ["spa"] },
        { id: "yoga", title: "Sunrise Yoga", description: "On the upper deck, 6am.", icon: "leaf", highlightIn: ["spa"] },
        { id: "walks", title: "Scenic Waterfront Walks", description: "Quiet paths along the lake.", icon: "wave", highlightIn: ["spa"] },
        { id: "trails", title: "Nature & Hiking Trails", description: "Forested trails a short drive away.", icon: "mountain", highlightIn: ["spa"] },
      ],
    },
    {
      id: "garden",
      index: 9,
      name: "Garden",
      kicker: "Chapter 10",
      scrollAnchor: 0.9,
      panorama: "/panoramas/garden-1.jpg",
      camera: cam(0.18, 60, Math.PI / 2),
      theme: "light",
      headline: "A floating garden.",
      body: "Lavender, marigold and weeping willows — a small garden at the entrance, tended daily.",
      hotspots: [],
    },
    {
      id: "booking",
      index: 10,
      name: "Reserve",
      kicker: "Chapter 11",
      scrollAnchor: 1.0,
      panorama: "/panoramas/deck-main.jpg",
      camera: cam(0.20, 60, Math.PI / 2),
      theme: "dark",
      headline: "Stay with us.",
      body: "Confirm your suite on the lake.",
      hotspots: [],
    },
  ],
};

export const allHotels: Hotel[] = [hotel];
